### ISSUE TITLE
Upgrade to 0.8.0

### ISSUE THREAD

**Issue by ibobo** [alexandre-abrioux/golem-node#13]
Please can you upgrade this to the latest version?

**Comment by alexandre-abrioux** [comment]
Hey! Sure I will update to v0.8.0 once they release it.
For now they only released candidates: https://github.com/golemfactory/yagna/releases
I'm subscribed to their release notifications but don't hesitate to ping me here again once it's out.

**Comment by ibobo** [comment]
Sorry, it seemed it was a final release...
