### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by Milo123459** [alexandre-abrioux/golem-node#26]

**Comment by alexandre-abrioux** [comment]
@Milo123459 I don't have access to an AMR environment, but I'm happy to add support if you can confirm that the node runs properly on your end. Try building the Docker image manually:
```sh
git pull git@github.com:alexandre-abrioux/golem-node.git
cd golem-node
docker build -t aabrioux/golem-node:latest Dockerfile
```
; then follow the [Usage](https://github.com/alexandre-abrioux/golem-node#arrow_forward-usage) section to set-up your node and run it. Let me know how that goes 🙂

**Comment by Milo123459** [comment]
I've since learnt Golem isn't suitable for aarch devices.
