### ISSUE TITLE
Upgrade to Yagna 14

### ISSUE THREAD

**Issue by MX10-AC2N** [alexandre-abrioux/golem-node#39]
I see Yagna released v14 why do you not update your docker release ?

**Comment by alexandre-abrioux** [comment]
It should be done automatically. I'll have a look to see what's broken.

**Comment by alexandre-abrioux** [comment]
There was indeed an issue with the automated workflow, thanks for noticing. This is now fixed and the version was updated: [v0.14.0](https://github.com/alexandre-abrioux/golem-node/releases/tag/v0.14.0).
