### ISSUE TITLE
need help buillding image for arm64 

### ISSUE THREAD

**Issue by syahpian** [alexandre-abrioux/golem-node#44]
hello, 

im trying to build the image for arm64 (raspberry pi 4) but encounter an error

 1 warning found (use --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 10)
root@LocalNodePI2:~/golem-node#

using ubuntu server 22.04 lts for arm64

not sure how to solve it since im new to this

regards

**Comment by alexandre-abrioux** [comment]
Hi @syahpian, I've just added new parameters in the `Dockerfile` so we can test this (see [commit](https://github.com/alexandre-abrioux/golem-node/commit/40012dfb8f8e1975780259b6099008b4c2c688bc)). I don't have access to an AMR environment, but I'm happy to add support if you can confirm that the node runs properly on your end. Try building the Docker image manually:
```sh
git pull
docker build \
  --tag aabrioux/golem-node:latest \
  --build-arg YA_CORE_ARCH=linux_aarch64 \
  --build-arg YA_WASI_ARCH=osx \
  docker
```
Then, you can run the `docker-compose.yml` file like described in the [README](https://github.com/alexandre-abrioux/golem-node?tab=readme-ov-file#arrow_forward-usage). I'm not sure about the `YA_WASI_ARCH` argument, if you should use `osx` or `linux`. Try with both, see what works, and let me know 🙂

**Comment by alexandre-abrioux** [comment]
`YA_WASI_ARCH` can be configured using the command I sent you above, no need to edit any file.

**Comment by syahpian** [comment]
already try both 

docker build \
  --tag aabrioux/golem-node:latest \
  --build-arg YA_CORE_ARCH=linux_aarch64 \
  --build-arg YA_WASI_ARCH=osx \
  docker

and 

docker build \
  --tag aabrioux/golem-node:latest \
  --build-arg YA_CORE_ARCH=linux_aarch64 \
  --build-arg YA_WASI_ARCH=linux \
  docker

same error

[2024-07-02T13:58:05Z ERROR golemsp] EOF
>>> Running pre-install script
>>> Importing resources
>>> Starting Golem
[2024-07-02T13:58:32Z ERROR golemsp] EOF

regards

**Comment by alexandre-abrioux** [comment]
Thanks. Unfortunately, I won't be able to help you more as I don't have access to an ARM device. I'm not sure which binaries you should use or if it's even possible to run the node on ARM. I'd advise you to reach out to Golem's team, either on GitHub (https://github.com/golemfactory/yagna) or Discord (https://chat.golem.network/). Let me know if you make it work!

**Comment by syahpian** [comment]
hello, 

it run when using old golem node folder (the one before you update to new line)

but i now getting this error on both osx and linux

[2024-07-03 02:18:34.089872 +08:00] INFO [exe-unit/src/runtime/process.rs:134] Executing "/usr/lib/yagna/plugins/ya-runtime-wasi" with ["offer-template"] from path Ok("/root/.local/share/ya-provider/exe-unit/work")
[2024-07-03 02:18:34.095709 +08:00] ERROR [exe-unit/src/bin.rs:357] IO error: Exec format error (os error 8)
Error: EOF while parsing a value at line 1 column 0
[2024-07-02T18:18:34Z ERROR golemsp::service] child provider exited too early: Ok(ExitStatus(unix_wait_status(256)))
[2024-07-02T18:18:34Z WARN  golemsp::service] provider exited with: Custom { kind: Other, error: "process exited too early" }


the way i do it is i compile first using new golem node folder version and then run it using old golem node folder version

regards

**Comment by syahpian** [comment]
i think something gone wrong after you make latest update on the file,

even on my docker desktop pc is having same error when pulling latest version of your github file


![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/dbce5ff2-739d-4a5c-a8b1-7c5cd70b8108)

pc spec

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/b3781b0b-c7b0-4bc9-b471-3e716392e043)

can you check what is the issue?

regards

**Comment by alexandre-abrioux** [comment]
I can't reproduce the error on my side 😕 @syahpian What is the result of this command with both images (your backup and the newer one):
```sh
docker run --rm aabrioux/golem-node:latest bash -c "sha1sum /usr/bin/golemsp"
```

**Comment by syahpian** [comment]
new version

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/3272543b-e538-42c5-97c6-0e10e9f160a1)

backup

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/d7042f31-b5c2-458a-b972-964236e14571)



regards

**Comment by alexandre-abrioux** [comment]
In your first screenshot, you have cloned the repository but you haven't built the image. Here is the full script:
```sh
# remove the existing Docker image
docker rmi aabrioux/golem-node:latest

# print the correct checksum from the image on Dockerhub (v0.15.2)
docker run --rm aabrioux/golem-node:0.15.2 bash -c "sha1sum /usr/bin/golemsp"

# clone the repo
git clone git@github.com:alexandre-abrioux/golem-node.git
cd golem-node

# build the image with the updated code
docker build -t aabrioux/golem-node:latest docker

# verify the checksum of your locally built image
docker run --rm aabrioux/golem-node:latest bash -c "sha1sum /usr/bin/golemsp"

# both checksums should be identical, if so, try to run the container
make setup
make up
```

**Comment by syahpian** [comment]
new version of golem-node

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/ef960609-f98a-4508-9e2a-f8e4b9318374)
![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/87397fb0-07bc-4f76-be94-1150274db785)
![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/69f98d7e-4083-4613-8186-bd04fb42b5ed)

old golem-node version ( using same command)

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/5c4244f5-a556-4642-b294-cdd406fa46ed)
![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/bfd39b1d-b3c5-430b-9e40-5823673de9f3)
![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/66cf9d06-12af-4294-8c93-0f2d7d7a52c7)

old golem-node version (using existing docker image)

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/50fb3646-5a4b-468d-ad28-deb272f35923)
![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/ed605f42-9055-4c45-a870-7d0bad463bd5)

regards

**Comment by alexandre-abrioux** [comment]
I'm not sure if it is my last change that broke your setup, or if it is because you're building the image yourself.

Could you test building the image from the previous commit:

```bash
git checkout e5c29c5f83cd867cf316880d1e7f77de3060b5aa
docker build -t aabrioux/golem-node:latest docker
make up
```

Does that still work?

**Comment by syahpian** [comment]
hello

using that command i get this

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/c602d27e-f391-4a2b-9892-dd4ac56d8b61)

same error as i open this ticket.

what i can say is, 

old golem-node version; can run image that i compile using latest golem node version but cannot be use to compile image
new golem node version: can compile image but cannot run the image that i compile using it

maybe the error only specific to my machine since i use wsl2 with docker desktop on windows 11 LTSC

regards

**Comment by alexandre-abrioux** [comment]
Hey @syahpian, in the screenshot, you built the image but did not run it (you forgot the `make up`).
What happens after?

```bash
git checkout e5c29c5f83cd867cf316880d1e7f77de3060b5aa
docker build -t aabrioux/golem-node:latest docker
make up
```

**Comment by syahpian** [comment]
![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/bea0d65f-da5e-40b2-84ab-a1810512b416)

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/9a5c1366-31de-4c67-bc60-d4837f103594)

it giving error on console,

regards

**Comment by alexandre-abrioux** [comment]
OK, great news. It's not because of the "new version" that this error occurs; even with the "old version," you have an issue when building the image locally. I'm not sure why, though.

**Comment by syahpian** [comment]
i see, so it really cause by my machine

and if it not too much hasle, can you try building multiarch image for x64 and arm64?

regards

**Comment by alexandre-abrioux** [comment]
I've built the image for arm64 👍
Please `git pull` the latest changes, then you can add the following in your `.env.local` to try the "beta" image:
```.env
DOCKER_IMAGE_TAG=master
```

Then use `make up` and let me know how it goes!

**Comment by syahpian** [comment]
hello,

thank you for biulding arm64 image

the result on my raspberry pi

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/34bf0235-5fad-4a3a-bc38-cedfbff294c9)
![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/5e939feb-ff4d-40c9-89cb-7319cded782c)

it still giving same error

also, for my pc, do you think i need to reinstall windows?

regards

**Comment by syahpian** [comment]
thank you for the arm64 image

it running on raspbbery pi now. 

but i getting new error

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/7efa1deb-c909-4aa4-9aab-fcb3c391988b)

regards

**Comment by syahpian** [comment]
update:

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/e59435ad-ed1d-45fb-819f-8ca2d4c14838)

after compiling latest qemu, there still error

![image](https://github.com/alexandre-abrioux/golem-node/assets/12189144/12f6164d-b37c-4b27-93c7-cd98d81419e3)

regards

**Comment by alexandre-abrioux** [comment]
Thank you for testing @syahpian, and sorry that we couldn't make it work.

After digging some more, it looks like aarch64 (arm64) is not supported at the moment:
- There are aarch64 binaries for the provider, see https://github.com/golemfactory/yagna/releases/tag/v0.15.2 ; but there are no such binary for the runtime VM, see https://github.com/golemfactory/ya-runtime-vm/releases/tag/v0.3.0
- The official provider installation script simply won't install anything on aarch64: https://join.golem.network/as-provider ; see on line 181, it throws an error: "We do not support running a provider on ARM devices yet. Please use an x86_64 machine to install the provider."
- There was community support, but it has been abandoned: https://github.com/MarijnStevens/yagna-binaries

I will make a last attempt at reaching the Golem team on Discord, but it looks impossible at the moment 😕

**Comment by syahpian** [comment]
i see, 

thank you very much for your cooperation, realy appreciate it 💯 

i gonna close this ticket

regards
