### ISSUE TITLE
golem node auto pricing on golem image

### ISSUE THREAD

**Issue by syahpian** [alexandre-abrioux/golem-node#51]
hello, 

just want to ask, is it possible to use auto pricing with golem node docker image?

for example this one

https://github.com/jedbrooke/golem-price-updater

regards

**Comment by alexandre-abrioux** [comment]
The script is looking for `~/.local/bin/golemsp`, see here: https://github.com/jedbrooke/golem-price-updater/blob/master/golem-price-update.py#L115

You could create the file yourself; with this content, it should work:
```sh
#!/bin/sh
docker exec -ti golem-node_node golemsp "$@"
```

**Comment by syahpian** [comment]
i see, 

thanks, will try that

also, is there any plan to include autopricing into the golem node image?

regards

**Comment by alexandre-abrioux** [comment]
Hi @syahpian, I have no plan at the moment; I didn't know about this script before and have not used it personally. PRs are welcome. It would need a new Dockerfile to wrap this script in a Docker image, a new service in the docker-compose that is optionally started, and new environment variables to configure it.
